### ISSUE TITLE
Bundle bugs

### ISSUE THREAD

**Issue by ColCh** [webix-hub/tracker#138]
In file : **codebase / webix.css**

``` css
#image .loadingImage{background-image:url(imgs/loading.png);background-repeat:no-repeat;background-position:center}
```

No file\dir **imgs/loading.png**

``` css
@font-face{font-family:'PT Sans';font-style:normal;font-weight:400;src:local('PT Sans'),local('PTSans-Regular'),url(fonts/PTS-webfont.eot) format('embedded-opentype'),url(fonts/PTS-webfont.woff) format('woff'),url(fonts/PTS-webfont.tft) format('truetype')}
```

May be a typo... No font **url(fonts/PTS-webfont.tft)** but **url(fonts/PTS-webfont.ttf)** (**tft** and **ttf**).
